logging:
  level: debug
  config: classpath:logback.xml
spring:
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///dy
org:
  tlh:
    datasource:
      names: d1
      d1:
        driver-class-name: org.gjt.mm.mysql.Driver
        username: root
        password: 123456
        url: jdbc:mysql:///dy1
uncode:
  schedule:
    zk-connect: 127.0.0.1:2181
    zk-username: admin
    zk-password: 123456